# Generated by Django 3.0.2 on 2023-08-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_auto_20230830_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFeedbackRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
